accelerator: null
accumulate_grad_batches: 1
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 16
benchmark: false
bert_config_dir: bert-base-uncased
bert_dropout: 0.1
bert_max_length: 200
best_dev_f1: 0.0
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: ./data/nl4opt/
dataname: nl4opt-task1
default_root_dir: ./trained_model/spanner_bert-base-uncased_85822412
deterministic: false
distributed_backend: ddp
epsilon: 0.001
es_threshold: 1.0e-06
fast_dev_run: false
final_div_factor: 10000.0
flush_logs_every_n_steps: 100
fp_epoch_result: ./trained_model/spanner_bert-base-uncased_85822412/epoch_results.txt
gpus: 0,
gradient_clip_algorithm: norm
gradient_clip_val: 1.0
label2idx_list:
- !!python/tuple
  - LIMIT
  - 1
- !!python/tuple
  - CONST_DIR
  - 2
- !!python/tuple
  - VAR
  - 3
- !!python/tuple
  - PARAM
  - 4
- !!python/tuple
  - OBJ_NAME
  - 5
- !!python/tuple
  - OBJ_DIR
  - 6
- !!python/tuple
  - O
  - 0
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.0001
max_epochs: 30
max_spanLen: 6
max_steps: null
max_time: null
min_epochs: null
min_steps: null
modelName: spanner_bert-base-uncased
model_dropout: 0.1
morph2idx_list:
- !!python/tuple
  - isupper
  - 1
- !!python/tuple
  - islower
  - 2
- !!python/tuple
  - istitle
  - 3
- !!python/tuple
  - isdigit
  - 4
- !!python/tuple
  - other
  - 5
morph_emb_dim: 100
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_class: 7
neg_span_weight: 0.5
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
optimizer: adamw
overfit_batches: 0.0
param_name: epoch30_batchsize16_lr1e-4_maxlen200
patience: 5
plugins: null
precision: 16
prepare_data_per_node: true
pretrained_checkpoint: ''
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
random_int: '85822412'
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
spanLen_emb_dim: 100
span_combination_mode: x,y
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
tokenLen_emb_dim: 50
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
use_morph: true
use_prune: false
use_spanLen: true
use_span_weight: true
use_tokenLen: false
val_check_interval: 0.5
warmup_steps: 0
weight_decay: 0.01
weights_save_path: null
weights_summary: top
workers: 0
